name: innlite_mobile
description: The Android + iOS cross-platform INNLITE mobile app

publish_to: 'none'

version: 3.2.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  grouped_list: ^4.0.0
  fluttertoast: ^8.0.6
  shared_preferences: ^2.1.2
  flutter_svg: ^0.23.0+1
  http: 0.13.1
  video_player: ^2.0.2
  flutter_html: ^3.0.0-alpha.6
  webview_flutter_plus: ^0.2.3
  better_player: ^0.0.44
  connectivity: ^3.0.6
  flutter_multiselect: ^1.0.0
  getwidget: ^2.0.4
  flick_video_player: ^0.5.0
  flutter_webview_plugin: ^0.4.0
  external_app_launcher: ^3.1.0
  jiffy: ^4.1.0

  provider: ^6.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - icons/
    - assets/
    - assets/TestPage.html
    - assets/mp.html
    - css/common.css
    - assets/index.html
    - assets/data.js
    - assets/202.mp4
    - assets/203.mp4
    - assets/evo.png
    - assets/evohtml5player-latest-unminify.bundle.js